### ISSUE TITLE
ocm search by version.id compares strings, not semantic versions

### ISSUE THREAD

**Issue by T0MASD** [openshift-online/ocm-cli#301]
When ocm does version.id sorting, it appears as if it uses "strings" thus making results appear in wrong order, it causes following behavior 
< 4.7.7
```
$ ocm list clusters --columns=version.id --parameter "search=id='myclusterid' and version.id > 'openshift-v4.7.0' and version.id < 'openshift-v4.7.7'"
VERSION ID                        
openshift-v4.7.6                 
```
< 4.7.9
```
$ ocm list clusters --columns=version.id --parameter "search=id='myclusterid' and version.id > 'openshift-v4.7.0' and version.id < 'openshift-v4.7.9'"
VERSION ID                        
openshift-v4.7.6               
```
< 4.7.10 starts to break
```
$ ocm list clusters --columns=version.id --parameter "search=id='myclusterid' and version.id > 'openshift-v4.7.0' and version.id < 'openshift-v4.7.10'"
VERSION ID
```
It would be great if search was semantic versioning aware

**Comment by jhernand** [comment]
The `ocm` command doesn't do any sorting of the output by version; sorting is done by the server. You are right that it sorts by string and not by semantic version. Changing that would be difficult because the server delegates all searches to the underlying PostgreSQL database, and the database doesn't provide any simple mechanism to compare semantic versions.

I am closing this because if we want a fix it should be in the server and not in the `ocm` tool. Please open an issue in the Jira SDA board.
