### ISSUE TITLE
CI for this repo?

### ISSUE THREAD

**Issue by cblecker** [openshift-online/ocm-cli#67]
Should we look into hooking up prow CI for this repo?

**Comment by vkareh** [comment]
that'd be awesome for automatically tagging reviewers and getting auto-merge!

**Comment by vkareh** [comment]
Example configuration for reference (this is what was done for moactl):
* https://github.com/openshift/release/pull/9633/files
* https://github.com/openshift/moactl/pull/25/files

**Comment by cben** [comment]
Huh, turns out we're connected to a CI, a Jenkins maintained by app-sre.  
pr_check.sh file is there for a long time, so I guess the CI has worked for a long time, I just didn't realize it.
Example run: https://ci.ext.devshift.net/job/openshift-online-ocm-cli-gh-pr-check/304/console

however, the CI output is not public-accessible.  Logging in with an unrelated github user I get "Access Denied
anpc is missing the Overall/Read permission".  This is bad for public project, external contributors should be able to see CI output for their PRs.  I'll ask app-sre about that.

**Comment by jhernand** [comment]
CI now runs in GitHub actions. Both the definition of jobs and the logs are accessible to anyone.
